services:
  - type: web
    name: alexa-admin-x
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 60
    envVars:
      - key: RENDER_EXTERNAL_URL
        value: https://alexa-admin-x.onrender.com
